apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suricata-monitoring

resources:
- ../../base/namespace.yaml
- ../../base/configmap.yaml
- ../../base/secret.yaml
- ../../base/postgres-statefulset.yaml
- ../../base/dashboard-service.yaml
- deployment.yaml
- ingress.yaml
# Uncomment if using NFS provisioner
# - nfs-provisioner.yaml

commonLabels:
  deployment-pattern: nfs
